### ISSUE TITLE
Hos can i uninstall?

### ISSUE THREAD

**Issue by utit** [gyan000/EOSConnect#7]
hello sir, i wanna remove eos connect.
how can i uninstall this?

**Comment by gyan000** [comment]
Hello,

You can run this command, inside the main directory. (/EOSConnect) :
` sudo ninja -C build uninstall`

What you should see :
```
EOSConnect$ sudo ninja -C build uninstall
ninja: Entering directory `build'
[0/1] /usr/bin/meson --internal uninstall
Deleted: /usr/local/share/metainfo/com.github.gyan000.eos-connect.appdata.xml
Deleted: /usr/local/share/applications/com.github.gyan000.eos-connect.desktop
Deleted: /usr/local/bin/com.github.gyan000.eos-connect
Deleted: /usr/local/share/glib-2.0/schemas/com.github.gyan000.eos-connect.gschema.xml

Uninstall finished.

Deleted: 4
Failed: 0
```

**Comment by utit** [comment]
> Hello,
> 
> You can run this command, inside the main directory. (/EOSConnect) :
> ` sudo ninja -C build uninstall`
> 
> What you should see :
> 
> ```
> EOSConnect$ sudo ninja -C build uninstall
> ninja: Entering directory `build'
> [0/1] /usr/bin/meson --internal uninstall
> Deleted: /usr/local/share/metainfo/com.github.gyan000.eos-connect.appdata.xml
> Deleted: /usr/local/share/applications/com.github.gyan000.eos-connect.desktop
> Deleted: /usr/local/bin/com.github.gyan000.eos-connect
> Deleted: /usr/local/share/glib-2.0/schemas/com.github.gyan000.eos-connect.gschema.xml
> 
> Uninstall finished.
> 
> Deleted: 4
> Failed: 0
> ```

thankyou for help
